### ISSUE TITLE
Rails.js not preventing double submit 

### ISSUE THREAD

**Issue by scottillogical** [rails/jquery-ujs#208]
Using form :remote and jquery-rails (1.0.14)

You can easily double submit on firefox 6 and probably most other browsers.
I worked around by adding code like this

```
$('#form').live('ajax:beforeSend', function(evt, xhr, settings){
  // prevent double submit
  $(':submit', this).click(function() {
    return false;
  });
});
```

**Comment by cs0511** [comment]
HI @jkaipr  I probably have the same issue as yours. Could you tell me how you fix it? Many thanks.

**Comment by jkaipr** [comment]
Hi @cs0511 My problem was caused by using jquery_ujs along with bootstrap-validator [nowadays it's called formvalidation](http://formvalidation.io/). It can also be caused by many other libraries which are somehow tweaking form behaviour. The solution that helped me is described in the link mentioned in my previous comment [bootstrap-validator-rails gem](https://github.com/jkaipr/bootstrap-validator-rails). You just have to scroll down to the section **Together with Rails remote form**.

If you don't use bootstrap-validator aka formvalidation, then you have some other javascript troublemaker in your application. If you know how to use Chrome dev tools, the description of how to find out which piece of code is submitting the form is in my previous comment. If you don't, you'll have to learn it.

You have to open the dev tools before submitting the problematic form. After it was submitted, look into dev tools Network tab and find the submit initiator.

**Comment by cs0511** [comment]
@jkaipr Thank you very much. You saved me a lot of time. I had the same issue as yours.

Again thanks. :+1:
