### ISSUE TITLE
ajax link inside ajax form is not functioning properly

### ISSUE THREAD

**Issue by torkale** [rails/jquery-ujs#323]
```html
<form accept-charset="UTF-8" action="/users/sign_in" data-remote="true" method="post">
<a href="/users/password/new.js" data-remote="true">Forgot Password?</a>
</form>
```

the data-remote of the link inside the form is ignored

**Comment by espen** [comment]
I know this issue is outdated but just writing here as Google led me here and I guess this issue should be closed unless a failing test can be provided.

Are you perhaps using stopPropagation somewhere else? I was facing this issue as well and I was using stopPropagation on elements within the dynamic content.

**Comment by adzap** [comment]
Having this issue too. My particular issue I found to be from the bubbling of link click ajax:* events bubbled up to the form ajax:success before my global ajax:success intended for links attached to document. The form behaviour was calling other function which stopped propagation. 

I fixed the issue by checking in the form ajax:success event was attached to the form itself rather than bubbled from the link

```ruby
event.target != this
```
