### ISSUE TITLE
How to unbind data-remote events

### ISSUE THREAD

**Issue by georgeselkhoury** [rails/jquery-ujs#356]
Hi everybody,

I need to unbind data-remote events. (basically I want the click to happen with no-ajax and open a new window).

ajax:before returning false does not work as it would cancel the click event which I still want to happen.

Any idea how to do the below?

if (certain condition) {
$(''a[date-remote=true] //disable/unbind rails click events on this selector?
}

**Comment by newdark** [comment]
I have been trying to use 
```js
$(document).undelegate('.selector', 'click.rails')
```
and have yet to get it to work. The code above
```js
$(document).undelegate($.rails.linkClickSelector, 'click.rails');
```
works but it unbinds everything. Another I don't total get is that jQuery recomends using on rather then delegate so it might be a bug with the newer versions of jquery.

**Comment by JangoSteve** [comment]
@newdark, I'm not in front of my computer, so I can't check and I don't remember off-hand, but I'm not sure it's possible to unbind a handler for a subset of the selectors that were bound.

Using `delegate` over `bind` won't cause any bugs, as they use the same underlying code, and the jquery core team has stated that delegate won't be going anywhere since it's only one line of code in the jquery codebase. I personally prefer `delegate` over `on`, as it's clearer with `on`'s API which will bind with two arguments and delegate with three arguments (thus making it difficult to see at a glance what is actually happening with code that uses `on`). But that's basically the only reason we use `delegate`, so there's nothing more going on there.
